# 代码生成时间: 2025-08-14 13:50:57
# test_data_generator.rb
# This script generates test data for a Rails application.

require 'active_record'
require 'faker'
require 'factory_bot_rails'
require 'pry'

# Set up ActiveRecord connection to your database
ActiveRecord::Base.establish_connection(
  adapter:  'sqlite3',
  database: 'test_database.sqlite3'
)

# Define a sample model for demonstration purposes
class User < ActiveRecord::Base
  # No need to define any columns as they will be generated by the test data
end

# Define factories using FactoryBot
FactoryBot.define do
  factory :user do
    sequence(:email) { |n| "user#{n}@example.com" }
    first_name { Faker::Name.first_name }
    last_name { Faker::Name.last_name }
    age { Faker::Number.within(range: 18..65) }
  end
end

# Function to generate test data
def generate_test_data(num_users)
  # Ensure the number of users is a positive integer
  raise ArgumentError, 'Number of users must be a positive integer' unless num_users.is_a?(Integer) && num_users > 0
  
  num_users.times do |n|
    FactoryBot.create(:user)
  end
  puts "Generated #{num_users} test users."
rescue ActiveRecord::RecordInvalid => e
  puts "An error occurred while generating test data: #{e.message}"
end

# Example usage
# Uncomment the line below to generate 10 test users
# generate_test_data(10)
